export const LAYER_CONV = 'LAYER_CONV';
export const LAYER_MAXPOOL = 'LAYER_MAXPOOL';
export const LAYER_INPUT = 'LAYER_INPUT';
export const LAYER_FULLY_CONNECTED = 'LAYER_FULLY_CONNECTED';

export const ACTIVATION_RELU = 'ACTIVATION_RELU';
export const ACTIVATION_TANH = 'ACTIVATION_TANH';
export const ACTIVATION_LINEAR = 'ACTIVATION_LINEAR';
export const ACTIVATION_SOFTMAX = 'ACTIVATION_SOFTMAX';

export const INIT_ZEROS = 'INIT_ZEROS';
export const INIT_RANDN = 'INIT_RANDN';
export const INIT_CHARS = 'INIT_CHARS';
