LAYER_CONV = 'LAYER_CONV'
LAYER_MAXPOOL = 'LAYER_MAXPOOL'
LAYER_INPUT = 'LAYER_INPUT'
LAYER_FULLY_CONNECTED = 'LAYER_FULLY_CONNECTED'

ACTIVATION_RELU = 'ACTIVATION_RELU'
ACTIVATION_TANH = 'ACTIVATION_TANH'
ACTIVATION_LINEAR = 'ACTIVATION_LINEAR'
ACTIVATION_SOFTMAX = 'ACTIVATION_SOFTMAX'

INIT_ZEROS = 'INIT_ZEROS'
INIT_RANDN = 'INIT_RANDN'
